gui:
  # Rose Pine Moon
  theme:
    activeBorderColor:
      - "#3e8fb0"
      - bold
    inactiveBorderColor:
      - "#6e6a86"
    searchingActiveBorderColor:
      - "#ea9a97"
      - bold
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#3e8fb0"
    inactiveViewSelectedLineBgColor:
      - "#393552"
      - bold
    cherryPickedCommitFgColor:
      - "#2a273f"
    cherryPickedCommitBgColor:
      - "#ea9a97"
    markedBaseCommitFgColor:
      - "#9ccfd8"
    markedBaseCommitBgColor:
      - "#f6c177"
    unstagedChangesColor:
      - "#eb6f92"
    defaultFgColor:
      - "#e0def4"
os:
  editPreset: "nvim"
git:
  pagers:
    - pager: delta --dark --paging=never --color-only --plus-emph-style="bold white green" --minus-emph-style="bold white red" --plus-style="white "#005000""  --minus-style="white "#80001a"" --line-numbers
